import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderRef from "@/Components/Header";

import { PoppinsFont, cn } from "@/Utils";
import Footer from "@/Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={PoppinsFont.className}>
        <HeaderRef />
        <main className={cn("w-full")}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
